# Generated by Django 4.2.2 on 2023-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
