# Generated by Django 4.2.2 on 2023-07-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_transaction_id_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.coin'),
            preserve_default=False,
        ),
    ]
