# Generated by Django 4.2.2 on 2023-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_transaction_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gas',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='gas_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
