# Generated by Django 4.2.2 on 2023-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_transaction_analytics_t_created_23de1f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('amount', models.FloatField()),
                ('commission', models.FloatField()),
                ('total_sell', models.FloatField()),
                ('total_buy', models.FloatField()),
                ('total_count_buy', models.IntegerField()),
                ('total_count_sell', models.IntegerField()),
                ('total_sell_price', models.IntegerField()),
                ('total_buy_price', models.IntegerField()),
            ],
        ),
    ]
