# Generated by Django 4.2.2 on 2023-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_walletstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletstat',
            name='amount',
        ),
        migrations.AddField(
            model_name='walletstat',
            name='created_on',
            field=models.DateTimeField(default='2023-01-01 00:00'),
            preserve_default=False,
        ),
    ]
