# Generated by Django 4.2.2 on 2023-07-29 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0015_alter_walletstat_address_alter_walletstat_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wallets', models.ManyToManyField(blank=True, null=True, to='analytics.wallet', verbose_name='Отслеживаемые кошельки')),
            ],
        ),
    ]
