# Generated by Django 4.2.2 on 2023-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_whale'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='telegram',
            field=models.TextField(default='durov'),
        ),
    ]
