# Generated by Django 4.2.2 on 2023-08-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_whale_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='ticker',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
