# Generated by Django 4.2.2 on 2023-08-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_coin_address_coin_ticker_alter_coin_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='price',
        ),
        migrations.AddField(
            model_name='coin',
            name='abi',
            field=models.TextField(null=True),
        ),
    ]
