# Generated by Django 4.2.2 on 2023-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_remove_coin_price_coin_abi'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
