# Generated by Django 4.2.2 on 2023-08-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_coin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletstat',
            name='pnl_unrelease',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
